
charge_pose: [3.95, -1.428, -2.992]  #josh

path0: [4.769, -3.663, 0.104]   #jan
path1: [5.203, -7.752, -1.373]  #birgit
path2: [-3.525, 6.018, -2.9]    #alex
path3: [-6.767, 5.315, -2.9]    #benny
path4: [-10.22, 4.7, -1.5]  #kai
path5: [10.258, 7.553, -1.4]   #felipe

