blue: [0,0,1]
red: [1,0,0]
green: [0,1,0]
white: [1,1,1]
black: [0,0,0]
off: [0,0,0]

blue_fast_pulse:   [0,0,1 ,0,0,0.2]
blue_medium_pulse: [0,0,1 ,0,0,0.1]
blue_slow_pulse:   [0,0,1 ,0,0,0.05]

red_fast_pulse:   [1,0,0,0.2,0,0]
red_medium_pulse: [1,0,0,0.1,0,0]
red_slow_pulse:   [1,0,0,0.05,0,0]

green_fast_pulse:   [0,1,0, 0,0.2,0]
green_medium_pulse: [0,1,0, 0,0.1,0]
green_slow_pulse:   [0,1,0, 0,0.05,0]

white_fast_pulse:   [1,1,1,0.2,0.2,0.2]
white_medium_pulse: [1,1,1,0.1,0.1,0.1]
white_slow_pulse:   [1,1,1,0.05,0.05,0.05]
